In [1]:
#import packages 

import plotly.express as px
import pandas as pd
import numpy as np
import pycountry_convert as pc
import warnings
warnings.filterwarnings('ignore')

In [2]:
cols = ['iso_code','continent','location','date','total_cases','new_cases','total_deaths','new_deaths','icu_patients','population','gdp_per_capita','life_expectancy']

In [3]:
# importing datasets

GIT_DATA= 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv'
VACCINE_DATA = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv'

covid_case_git = pd.read_csv(GIT_DATA, index_col=False, na_values =("N/A", "NA", "--", " ", "-"),usecols = cols)
vaccine_data = pd.read_csv(VACCINE_DATA, index_col=False, na_values =("N/A", "NA", "--", " ", "-"))

In [4]:
covid_case_git

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,icu_patients,population,gdp_per_capita,life_expectancy
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,39835428.0,1803.987,64.83
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,39835428.0,1803.987,64.83
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,39835428.0,1803.987,64.83
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,39835428.0,1803.987,64.83
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,39835428.0,1803.987,64.83
...,...,...,...,...,...,...,...,...,...,...,...,...
184974,ZWE,Africa,Zimbabwe,2022-05-05,248050.0,0.0,5471.0,0.0,NaN,15092171.0,1899.775,61.49
184975,ZWE,Africa,Zimbabwe,2022-05-06,248214.0,164.0,5473.0,2.0,NaN,15092171.0,1899.775,61.49
184976,ZWE,Africa,Zimbabwe,2022-05-07,248214.0,0.0,5473.0,0.0,NaN,15092171.0,1899.775,61.49
184977,ZWE,Africa,Zimbabwe,2022-05-08,248352.0,138.0,5476.0,3.0,NaN,15092171.0,1899.775,61.49
184978,ZWE,Africa,Zimbabwe,2022-05-09,248536.0,184.0,5479.0,3.0,NaN,15092171.0,1899.775,61.49

In [5]:
vaccine_data

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million,daily_people_vaccinated,daily_people_vaccinated_per_hundred
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100852,Zimbabwe,ZWE,2022-05-04,10389266.0,5882608.0,3714905.0,791753.0,47215.0,17194.0,68.84,38.98,24.61,5.25,1139.0,4596.0,0.030
100853,Zimbabwe,ZWE,2022-05-05,NaN,NaN,NaN,NaN,NaN,21512.0,NaN,NaN,NaN,NaN,1425.0,4422.0,0.029
100854,Zimbabwe,ZWE,2022-05-06,10482750.0,5898150.0,3777867.0,806733.0,NaN,25407.0,69.46,39.08,25.03,5.35,1683.0,4744.0,0.031
100855,Zimbabwe,ZWE,2022-05-07,10549825.0,5909962.0,3827660.0,812203.0,67075.0,33709.0,69.90,39.16,25.36,5.38,2234.0,6161.0,0.041
100856,Zimbabwe,ZWE,2022-05-08,10609881.0,5922239.0,3867341.0,820301.0,60056.0,41296.0,70.30,39.24,25.62,5.44,2736.0,7762.0,0.051

In [6]:
# There are some city names and countries which are not in pycountry iso list. So removing those to make the continent column correct.

covid_case_git.drop(covid_case_git[covid_case_git["location"] == "International" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Northern Cyprus" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "World" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Africa" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Europe" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "European Union" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Asia" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "High income" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Low income" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Lower middle income" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Upper middle income" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "North America" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "South America" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Oceania" ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["location"] == "Bolivia (Plurinational State of)" ].index, inplace = True)

In [7]:
covid_case_git.isna().sum()

iso_code                0
continent               0
location                0
date                    0
total_cases          6542
new_cases            6816
total_deaths        24650
new_deaths          24868
icu_patients       149777
population              0
gdp_per_capita      22351
life_expectancy      1751
dtype: int64

In [8]:
# removing blank values from total deaths and total cases so that it wont affect the graphs.
covid_case_git.drop(covid_case_git[covid_case_git["total_deaths"] == " " ].index, inplace = True)
covid_case_git.drop(covid_case_git[covid_case_git["total_cases"] == " " ].index, inplace = True)

In [9]:
covid_case_git.isna().sum()

iso_code                0
continent               0
location                0
date                    0
total_cases          6542
new_cases            6816
total_deaths        24650
new_deaths          24868
icu_patients       149777
population              0
gdp_per_capita      22351
life_expectancy      1751
dtype: int64

In [10]:
# dropping missing values so that it wont affect the graphs no other columns are removed since it is not using.
covid_case_git.dropna(subset=['total_cases', 'total_deaths'], inplace=True)

In [11]:
covid_case_git.isnull().sum()

iso_code                0
continent               0
location                0
date                    0
total_cases             0
new_cases             247
total_deaths            0
new_deaths            218
icu_patients       125263
population              0
gdp_per_capita      12637
life_expectancy       778
dtype: int64

Other missing vlaues are not removed since it is not using.

In [12]:
# checking duplicted values
covid_case_git.duplicated().sum()

0

In [13]:
# changing the date to pandas datetime format for both datasets

cd_date1 = pd.to_datetime(covid_case_git['date'].astype(str), format ='%Y/%m/%d')


cd_date2 = pd.to_datetime(vaccine_data['date'].astype(str), format ='%Y/%m/%d')

In [14]:
covid_case_git['month_year'] = pd.to_datetime(covid_case_git['date']).dt.to_period('M')
covid_case_git.head()

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,icu_patients,population,gdp_per_capita,life_expectancy,month_year
28,AFG,Asia,Afghanistan,2020-03-23,40.0,6.0,1.0,1.0,NaN,39835428.0,1803.987,64.83,2020-03
29,AFG,Asia,Afghanistan,2020-03-24,42.0,2.0,1.0,0.0,NaN,39835428.0,1803.987,64.83,2020-03
30,AFG,Asia,Afghanistan,2020-03-25,74.0,32.0,1.0,0.0,NaN,39835428.0,1803.987,64.83,2020-03
31,AFG,Asia,Afghanistan,2020-03-26,80.0,6.0,2.0,1.0,NaN,39835428.0,1803.987,64.83,2020-03
32,AFG,Asia,Afghanistan,2020-03-27,91.0,11.0,2.0,0.0,NaN,39835428.0,1803.987,64.83,2020-03

In [15]:
vaccine_data['month_year'] = pd.to_datetime(vaccine_data['date']).dt.to_period('M')
vaccine_data.head()

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million,daily_people_vaccinated,daily_people_vaccinated_per_hundred,month_year
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,2021-02
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003,2021-02
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003,2021-02
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003,2021-02
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003,2021-02

In [16]:
# creating separate columns for year and month for analysis.

covid_case_git['year'] = cd_date1.dt.year
covid_case_git['month'] = cd_date1.dt.month

vaccine_data['year'] = cd_date2.dt.year
vaccine_data['month'] = cd_date2.dt.month

In [17]:
# changing month values from Numbers to text

covid_case_git['date'] = pd.to_datetime(covid_case_git['date'])
covid_case_git['month'] = covid_case_git['date'].dt.month_name()

#covid_case_git['month_year'] = covid_case_git['year'].astype(str) +str('/')+ covid_case_git['month'].astype(str)
#covid_case_git['month_year'] = pd.to_datetime(covid_case_git['month_year'], format='%Y/%B')

vaccine_data['date'] = pd.to_datetime(vaccine_data['date'])
vaccine_data['month'] = vaccine_data['date'].dt.month_name()

In [18]:
covid_case_git.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 149210 entries, 28 to 184978
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   iso_code         149210 non-null  object
 1   continent        149210 non-null  object
 2   location         149210 non-null  object
 3   date             149210 non-null  datetime64[ns]
 4   total_cases      149210 non-null  float64
 5   new_cases        148963 non-null  float64
 6   total_deaths     149210 non-null  float64
 7   new_deaths       148992 non-null  float64
 8   icu_patients     23947 non-null   float64
 9   population       149210 non-null  float64
 10  gdp_per_capita   136573 non-null  float64
 11  life_expectancy  148432 non-null  float64
 12  month_year       149210 non-null  period[M]
 13  year             149210 non-null  int64
 14  month            149210 non-null  object
dtypes: datetime64[ns](1), float64(8), int64(1), object(4), period[M](1)
memory usage: 18.2+ MB

In [19]:
covid_case_git.to_csv("E:/covid_all.csv", index=False)

#### Vaccination dataset cleaning

In [20]:
# removing the places and countries which are not in the iso code3 list.
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Bolivia (Plurinational State of)" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Cote d'Ivoire" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Iran (Islamic Republic of)" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Kosovo" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Micronesia (Federated States of)" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Northern Mariana Islands (Commonwealth of the)" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "occupied Palestinian territory" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Pitcairn Islands" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Republic of Korea" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Saint Helena" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Sint Maarten" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "The United Kingdom" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Timor-Leste" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Venezuela (Bolivarian Republic of)" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Africa" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Asia" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Bonaire Sint Eustatius and Saba" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Curacao" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Democratic Republic of Congo" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "England" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Europe" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "European Union" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Faeroe Islands" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "High income" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Low income" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Lower middle income" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Upper middle income" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "North America" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "South America" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Oceania" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Northern Ireland" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Pitcairn" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Scotland" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Sint Maarten (Dutch part)" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Timor" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Wales" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "World" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Scotland" ].index, inplace = True)
vaccine_data.drop(vaccine_data[vaccine_data["location"] == "Africa" ].index, inplace = True)

In [21]:
def convert(row):
    cn_code = pc.country_name_to_country_alpha2(row.location, cn_name_format = "default")
    conti_code = pc.country_alpha2_to_continent_code(cn_code)
    return conti_code

In [22]:
vaccine_data["continent"] = vaccine_data.apply(convert, axis =1 )

In [23]:
# converting continent codes to Names
conti_names = {"AS": "Asia", "SA":"South America", "AN":"Antartica", "OC":"Oceania","EU":"Europe", "NA":"North America", "AF":"Africa"}
vaccine_data["continent"] = vaccine_data["continent"].map(conti_names)
vaccine_data

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million,daily_people_vaccinated,daily_people_vaccinated_per_hundred,month_year,year,month,continent
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,2021-02,2021,February,Asia
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003,2021-02,2021,February,Asia
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003,2021-02,2021,February,Asia
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003,2021-02,2021,February,Asia
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,NaN,34.0,1367.0,0.003,2021-02,2021,February,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100852,Zimbabwe,ZWE,2022-05-04,10389266.0,5882608.0,3714905.0,791753.0,47215.0,17194.0,68.84,38.98,24.61,5.25,1139.0,4596.0,0.030,2022-05,2022,May,Africa
100853,Zimbabwe,ZWE,2022-05-05,NaN,NaN,NaN,NaN,NaN,21512.0,NaN,NaN,NaN,NaN,1425.0,4422.0,0.029,2022-05,2022,May,Africa
100854,Zimbabwe,ZWE,2022-05-06,10482750.0,5898150.0,3777867.0,806733.0,NaN,25407.0,69.46,39.08,25.03,5.35,1683.0,4744.0,0.031,2022-05,2022,May,Africa
100855,Zimbabwe,ZWE,2022-05-07,10549825.0,5909962.0,3827660.0,812203.0,67075.0,33709.0,69.90,39.16,25.36,5.38,2234.0,6161.0,0.041,2022-05,2022,May,Africa
100856,Zimbabwe,ZWE,2022-05-08,10609881.0,5922239.0,3867341.0,820301.0,60056.0,41296.0,70.30,39.24,25.62,5.44,2736.0,7762.0,0.051,2022-05,2022,May,Africa

In [24]:
# checking null values
vaccine_data.isna().sum()

location                                   0
iso_code                                   0
date                                       0
total_vaccinations                     46573
people_vaccinated                      48973
people_fully_vaccinated                51126
total_boosters                         72269
daily_vaccinations_raw                 55210
daily_vaccinations                       325
total_vaccinations_per_hundred         46573
people_vaccinated_per_hundred          48973
people_fully_vaccinated_per_hundred    51126
total_boosters_per_hundred             72269
daily_vaccinations_per_million           325
daily_people_vaccinated                 1285
daily_people_vaccinated_per_hundred     1285
month_year                                 0
year                                       0
month                                      0
continent                                  0
dtype: int64

In [25]:
# removing null values so it wont affect the graphs.
vaccine_data.dropna(subset=['total_vaccinations_per_hundred','total_vaccinations','daily_vaccinations', 'people_fully_vaccinated'], inplace=True)

In [26]:
# checking duplicted values
vaccine_data.duplicated().sum()

0

In [27]:
vaccine_data.to_csv("E:\covid_vaccines.csv", index=False)
vaccine_data

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,daily_vaccinations_per_million,daily_people_vaccinated,daily_people_vaccinated_per_hundred,month_year,year,month,continent
78,Afghanistan,AFG,2021-05-11,504502.0,448878.0,55624.0,NaN,NaN,13921.0,1.27,1.13,0.14,NaN,349.0,10994.0,0.028,2021-05,2021,May,Asia
87,Afghanistan,AFG,2021-05-20,547901.0,470341.0,77560.0,NaN,NaN,4822.0,1.38,1.18,0.19,NaN,121.0,2385.0,0.006,2021-05,2021,May,Asia
91,Afghanistan,AFG,2021-05-24,573277.0,476367.0,96910.0,NaN,NaN,5692.0,1.44,1.20,0.24,NaN,143.0,1883.0,0.005,2021-05,2021,May,Asia
93,Afghanistan,AFG,2021-05-26,590454.0,479372.0,111082.0,NaN,NaN,6768.0,1.48,1.20,0.28,NaN,170.0,1631.0,0.004,2021-05,2021,May,Asia
94,Afghanistan,AFG,2021-05-27,593313.0,479574.0,113739.0,NaN,2859.0,6487.0,1.49,1.20,0.29,NaN,163.0,1319.0,0.003,2021-05,2021,May,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100851,Zimbabwe,ZWE,2022-05-03,10342051.0,5873685.0,3685351.0,783015.0,12172.0,12808.0,68.53,38.92,24.42,5.19,849.0,4606.0,0.031,2022-05,2022,May,Africa
100852,Zimbabwe,ZWE,2022-05-04,10389266.0,5882608.0,3714905.0,791753.0,47215.0,17194.0,68.84,38.98,24.61,5.25,1139.0,4596.0,0.030,2022-05,2022,May,Africa
100854,Zimbabwe,ZWE,2022-05-06,10482750.0,5898150.0,3777867.0,806733.0,NaN,25407.0,69.46,39.08,25.03,5.35,1683.0,4744.0,0.031,2022-05,2022,May,Africa
100855,Zimbabwe,ZWE,2022-05-07,10549825.0,5909962.0,3827660.0,812203.0,67075.0,33709.0,69.90,39.16,25.36,5.38,2234.0,6161.0,0.041,2022-05,2022,May,Africa
100856,Zimbabwe,ZWE,2022-05-08,10609881.0,5922239.0,3867341.0,820301.0,60056.0,41296.0,70.30,39.24,25.62,5.44,2736.0,7762.0,0.051,2022-05,2022,May,Africa